<?php
/**
 * Logs pages and posts generated by the plugin.
 *
 * @package SuperDirectory
 */

class SD_Content_Logger {

    /**
     * Register hooks.
     */
    public function register() {
        add_action( 'sd_log_generated_content', array( $this, 'log_content' ) );
        add_action( 'before_delete_post', array( $this, 'remove_content' ) );
        add_action( 'post_updated', array( $this, 'maybe_update_type' ), 10, 3 );
    }

    /**
     * Insert a record for a generated post or page.
     *
     * @param int $post_id Post ID.
     */
    public function log_content( $post_id ) {
        $post = get_post( $post_id );
        if ( ! $post ) {
            return;
        }

        global $wpdb;
        $table = $wpdb->prefix . 'sd_content_log';
        $wpdb->insert(
            $table,
            array(
                'post_id'   => $post_id,
                'post_type' => $post->post_type,
                'created_at'=> current_time( 'mysql' ),
            ),
            array( '%d', '%s', '%s' )
        );
    }

    /**
     * Remove log entry when a post is deleted.
     *
     * @param int $post_id Post ID.
     */
    public function remove_content( $post_id ) {
        global $wpdb;
        $table = $wpdb->prefix . 'sd_content_log';
        $wpdb->delete( $table, array( 'post_id' => $post_id ), array( '%d' ) );
    }

    /**
     * Update log if post type changes.
     *
     * @param int     $post_id     Post ID.
     * @param WP_Post $post_after  Post object following the update.
     * @param WP_Post $post_before Post object prior to the update.
     */
    public function maybe_update_type( $post_id, $post_after, $post_before ) {
        if ( $post_after->post_type === $post_before->post_type ) {
            return;
        }
        global $wpdb;
        $table = $wpdb->prefix . 'sd_content_log';
        $wpdb->update(
            $table,
            array( 'post_type' => $post_after->post_type ),
            array( 'post_id' => $post_id ),
            array( '%s' ),
            array( '%d' )
        );
    }

    /**
     * Retrieve logged entries.
     *
     * @return array
     */
    public function get_logged_content() {
        global $wpdb;
        $table = $wpdb->prefix . 'sd_content_log';
        return $wpdb->get_results( "SELECT post_id, post_type FROM $table ORDER BY id DESC" );
    }
}
